using System.Collections.Generic;

namespace JournalApp.AIAgent.Prompts
{
 public static class PromptLibrary
 {
 public static readonly string[] Categories = new[]
 {
 "Gratitude",
 "Reflection",
 "Goals",
 "Mindfulness",
 "Creativity"
 };

 //365 prompts, divided equally among categories (73 per category)
 public static readonly Dictionary<string, List<string>> PromptsByCategory = new()
 {
 ["Gratitude"] = new List<string>
 {
 "What is something small that made you happy today?",
 "Who is someone you appreciate and why?",
 "Describe a recent act of kindness you received.",
 "What is a comfort you enjoy that you often overlook?",
 "Name a friend or family member who has helped you recently.",
 "What is a favorite memory that brings you joy?",
 "What is a skill or talent you are grateful to have?",
 "Describe a place that makes you feel safe and thankful.",
 "What is a lesson you learned from a difficult experience?",
 "Who made you smile this week?",
 "What is a simple pleasure you enjoyed today?",
 "What is something about your health you are grateful for?",
 "What is a technology that makes your life easier?",
 "Describe a meal you enjoyed recently.",
 "What is a book, movie, or song you are thankful for?",
 "What is a part of your daily routine you appreciate?",
 "Who is someone you admire and why?",
 "What is a challenge you overcame and what did you gain?",
 "What is a natural beauty you witnessed recently?",
 "What is a tradition you cherish?",
 "What is a possession that brings you comfort?",
 "What is a recent accomplishment you are proud of?",
 "Who is someone who inspires you?",
 "What is a favorite hobby or pastime?",
 "What is a resource you have that you are grateful for?",
 "What is a mistake that taught you something valuable?",
 "What is a part of your personality you appreciate?",
 "What is a freedom you enjoy?",
 "What is a recent compliment you received?",
 "What is a favorite place to relax?",
 "What is a skill you are working on and grateful for the opportunity?",
 "What is a favorite family tradition?",
 "What is a recent positive change in your life?",
 "What is a favorite way to spend time outdoors?",
 "What is a favorite thing about your community?",
 "What is a favorite thing about your culture?",
 "What is a favorite thing about your home?",
 "What is a favorite thing about your job or studies?",
 "What is a favorite thing about your friends?",
 "What is a favorite thing about your family?",
 "What is a favorite thing about your pet(s)?",
 "What is a favorite thing about your city or town?",
 "What is a favorite thing about your country?",
 "What is a favorite thing about your favorite season?",
 "What is a favorite thing about your favorite holiday?",
 "What is a favorite thing about your favorite food?",
 "What is a favorite thing about your favorite drink?",
 "What is a favorite thing about your favorite book?",
 "What is a favorite thing about your favorite movie?",
 "What is a favorite thing about your favorite song?",
 "What is a favorite thing about your favorite artist?",
 "What is a favorite thing about your favorite sport?",
 "What is a favorite thing about your favorite activity?",
 "What is a favorite thing about your favorite place?",
 "What is a favorite thing about your favorite memory?",
 "What is a favorite thing about your favorite teacher?",
 "What is a favorite thing about your favorite mentor?",
 "What is a favorite thing about your favorite leader?",
 "What is a favorite thing about your favorite role model?",
 "What is a favorite thing about your favorite quote?",
 "What is a favorite thing about your favorite saying?",
 "What is a favorite thing about your favorite proverb?",
 "What is a favorite thing about your favorite poem?",
 "What is a favorite thing about your favorite story?",
 "What is a favorite thing about your favorite legend?",
 "What is a favorite thing about your favorite myth?",
 "What is a favorite thing about your favorite fairy tale?",
 "What is a favorite thing about your favorite fable?",
 "What is a favorite thing about your favorite parable?",
 "What is a favorite thing about your favorite anecdote?",
 "What is a favorite thing about your favorite joke?",
 "What is a favorite thing about your favorite riddle?",
 "What is a favorite thing about your favorite puzzle?",
 "What is a favorite thing about your favorite game?",
 "What is a favorite thing about your favorite toy?",
 "What is a favorite thing about your favorite childhood memory?",
 "What is a favorite thing about your favorite family member?",
 "What is a favorite thing about your favorite friend?"
 },
 ["Reflection"] = new List<string>
 {
 "What is something you learned about yourself this week?",
 "Describe a recent challenge and how you handled it.",
 "What is a decision you made that changed your perspective?",
 "What is a habit you want to improve and why?",
 "What is a mistake you made and what did you learn?",
 "What is a recent success and how did you achieve it?",
 "What is a fear you faced and what was the outcome?",
 "What is a value that is important to you?",
 "What is a belief you have questioned recently?",
 "What is a relationship that has changed and why?",
 "What is a goal you set and did you achieve it?",
 "What is a regret you have and what would you do differently?",
 "What is a risk you took and what did you learn?",
 "What is a time you felt proud of yourself?",
 "What is a time you felt disappointed and how did you cope?",
 "What is a time you felt grateful and why?",
 "What is a time you felt inspired and what inspired you?",
 "What is a time you felt challenged and how did you respond?",
 "What is a time you felt supported and who supported you?",
 "What is a time you felt misunderstood and why?",
 "What is a time you felt at peace and what contributed to it?",
 "What is a time you felt stressed and how did you manage it?",
 "What is a time you felt joyful and what brought you joy?",
 "What is a time you felt sad and how did you process it?",
 "What is a time you felt angry and how did you express it?",
 "What is a time you felt hopeful and what gave you hope?",
 "What is a time you felt hopeless and how did you recover?",
 "What is a time you felt confident and what contributed to it?",
 "What is a time you felt insecure and how did you overcome it?",
 "What is a time you felt loved and who made you feel that way?",
 "What is a time you felt lonely and how did you cope?",
 "What is a time you felt connected and what fostered that connection?",
 "What is a time you felt disconnected and why?",
 "What is a time you felt motivated and what drove you?",
 "What is a time you felt unmotivated and how did you get back on track?",
 "What is a time you felt creative and what sparked your creativity?",
 "What is a time you felt stuck and how did you move forward?",
 "What is a time you felt free and what contributed to that feeling?",
 "What is a time you felt restricted and how did you respond?",
 "What is a time you felt successful and what did you accomplish?",
 "What is a time you felt like you failed and what did you learn?",
 "What is a time you felt healthy and what contributed to your well-being?",
 "What is a time you felt unhealthy and how did you address it?",
 "What is a time you felt energetic and what fueled your energy?",
 "What is a time you felt tired and how did you rest?",
 "What is a time you felt curious and what did you explore?",
 "What is a time you felt bored and how did you find interest?",
 "What is a time you felt adventurous and what did you do?",
 "What is a time you felt cautious and why?",
 "What is a time you felt generous and what did you give?",
 "What is a time you felt selfish and why?",
 "What is a time you felt open-minded and what did you consider?",
 "What is a time you felt closed-minded and why?",
 "What is a time you felt optimistic and what were you hopeful about?",
 "What is a time you felt pessimistic and why?",
 "What is a time you felt patient and what were you waiting for?",
 "What is a time you felt impatient and why?",
 "What is a time you felt forgiving and who did you forgive?",
 "What is a time you felt unforgiving and why?",
 "What is a time you felt responsible and what were you responsible for?",
 "What is a time you felt irresponsible and why?",
 "What is a time you felt organized and what did you organize?",
 "What is a time you felt disorganized and how did you address it?",
 "What is a time you felt prepared and what were you preparing for?",
 "What is a time you felt unprepared and how did you manage?",
 "What is a time you felt decisive and what decision did you make?",
 "What is a time you felt indecisive and why?",
 "What is a time you felt focused and what were you working on?",
 "What is a time you felt distracted and how did you regain focus?"
 },
 ["Goals"] = new List<string>
 {
 "What is one goal you want to achieve this month?",
 "What steps can you take tomorrow to get closer to your goals?",
 "What is a long-term goal you are working toward?",
 "What is a short-term goal you can accomplish this week?",
 "What is a personal goal you have for yourself?",
 "What is a professional goal you want to achieve?",
 "What is a health goal you are pursuing?",
 "What is a financial goal you are saving for?",
 "What is a relationship goal you want to nurture?",
 "What is a learning goal you have set?",
 "What is a creative goal you want to explore?",
 "What is a travel goal you hope to fulfill?",
 "What is a skill you want to develop?",
 "What is a habit you want to build?",
 "What is a habit you want to break?",
 "What is a milestone you want to reach this year?",
 "What is a dream you want to pursue?",
 "What is a challenge you want to overcome?",
 "What is a fear you want to face?",
 "What is a risk you are willing to take?",
 "What is a project you want to start?",
 "What is a project you want to finish?",
 "What is a new experience you want to try?",
 "What is a routine you want to establish?",
 "What is a routine you want to change?",
 "What is a relationship you want to strengthen?",
 "What is a relationship you want to heal?",
 "What is a relationship you want to let go of?",
 "What is a place you want to visit?",
 "What is a book you want to read?",
 "What is a course you want to take?",
 "What is a certification you want to earn?",
 "What is a language you want to learn?",
 "What is a hobby you want to start?",
 "What is a hobby you want to improve?",
 "What is a sport you want to try?",
 "What is a competition you want to enter?",
 "What is a volunteer opportunity you want to pursue?",
 "What is a cause you want to support?",
 "What is a community you want to join?",
 "What is a community you want to contribute to?",
 "What is a leadership role you want to take on?",
 "What is a public speaking goal you have?",
 "What is a networking goal you want to achieve?",
 "What is a mentoring goal you want to pursue?",
 "What is a teaching goal you want to accomplish?",
 "What is a writing goal you want to reach?",
 "What is a creative project you want to complete?",
 "What is a fitness goal you want to achieve?",
 "What is a wellness goal you want to focus on?",
 "What is a mindfulness goal you want to practice?",
 "What is a gratitude goal you want to cultivate?",
 "What is a self-care goal you want to prioritize?",
 "What is a time management goal you want to improve?",
 "What is a productivity goal you want to set?",
 "What is a financial milestone you want to reach?",
 "What is a savings goal you want to accomplish?",
 "What is a spending habit you want to change?",
 "What is a giving goal you want to achieve?",
 "What is a sustainability goal you want to pursue?",
 "What is a technology goal you want to master?",
 "What is a digital detox goal you want to try?",
 "What is a social media goal you want to set?",
 "What is a reading goal you want to accomplish?",
 "What is a creative expression goal you want to explore?",
 "What is a family goal you want to nurture?",
 "What is a friendship goal you want to strengthen?",
 "What is a legacy goal you want to leave?",
 "What is a spiritual goal you want to pursue?",
 "What is a personal growth goal you want to achieve?",
 "What is a professional development goal you want to reach?",
 "What is a health and wellness goal you want to focus on?"
 },
 ["Mindfulness"] = new List<string>
 {
 "Describe a moment today when you felt present.",
 "What sensations do you notice right now?",
 "What is something you can see, hear, smell, taste, or touch in this moment?",
 "What is a mindful activity you enjoy?",
 "What is a breathing exercise that helps you relax?",
 "What is a grounding technique you use?",
 "What is a mindful walk you have taken recently?",
 "What is a meditation practice you find helpful?",
 "What is a way you bring awareness to your thoughts?",
 "What is a way you bring awareness to your emotions?",
 "What is a way you bring awareness to your body?",
 "What is a way you bring awareness to your surroundings?",
 "What is a way you bring awareness to your actions?",
 "What is a way you bring awareness to your words?",
 "What is a way you bring awareness to your intentions?",
 "What is a way you bring awareness to your habits?",
 "What is a way you bring awareness to your routines?",
 "What is a way you bring awareness to your relationships?",
 "What is a way you bring awareness to your environment?",
 "What is a way you bring awareness to your energy?",
 "What is a way you bring awareness to your breath?",
 "What is a way you bring awareness to your senses?",
 "What is a way you bring awareness to your posture?",
 "What is a way you bring awareness to your movement?",
 "What is a way you bring awareness to your stillness?",
 "What is a way you bring awareness to your silence?",
 "What is a way you bring awareness to your speech?",
 "What is a way you bring awareness to your listening?",
 "What is a way you bring awareness to your learning?",
 "What is a way you bring awareness to your growth?",
 "What is a way you bring awareness to your change?",
 "What is a way you bring awareness to your acceptance?",
 "What is a way you bring awareness to your letting go?",
 "What is a way you bring awareness to your gratitude?",
 "What is a way you bring awareness to your compassion?",
 "What is a way you bring awareness to your patience?",
 "What is a way you bring awareness to your kindness?",
 "What is a way you bring awareness to your generosity?",
 "What is a way you bring awareness to your forgiveness?",
 "What is a way you bring awareness to your joy?",
 "What is a way you bring awareness to your sorrow?",
 "What is a way you bring awareness to your fear?",
 "What is a way you bring awareness to your courage?",
 "What is a way you bring awareness to your hope?",
 "What is a way you bring awareness to your faith?",
 "What is a way you bring awareness to your love?",
 "What is a way you bring awareness to your connection?",
 "What is a way you bring awareness to your solitude?",
 "What is a way you bring awareness to your community?",
 "What is a way you bring awareness to your creativity?",
 "What is a way you bring awareness to your inspiration?",
 "What is a way you bring awareness to your motivation?",
 "What is a way you bring awareness to your discipline?",
 "What is a way you bring awareness to your relaxation?",
 "What is a way you bring awareness to your excitement?",
 "What is a way you bring awareness to your calm?",
 "What is a way you bring awareness to your stress?",
 "What is a way you bring awareness to your anxiety?",
 "What is a way you bring awareness to your peace?",
 "What is a way you bring awareness to your balance?",
 "What is a way you bring awareness to your harmony?",
 "What is a way you bring awareness to your resilience?",
 "What is a way you bring awareness to your adaptability?",
 "What is a way you bring awareness to your openness?",
 "What is a way you bring awareness to your curiosity?",
 "What is a way you bring awareness to your wonder?",
 "What is a way you bring awareness to your awe?",
 "What is a way you bring awareness to your humility?",
 "What is a way you bring awareness to your wisdom?"
 },
 ["Creativity"] = new List<string>
 {
 "Write a short story about a magical place.",
 "If you could invent something, what would it be?",
 "Describe a world where everyone has a superpower.",
 "Imagine a day in the life of your favorite animal.",
 "Write a poem about the changing seasons.",
 "Invent a new holiday and describe how it is celebrated.",
 "Describe a character who discovers a hidden talent.",
 "Write a letter to your future self.",
 "Describe a place you would like to visit in your dreams.",
 "Imagine you can talk to plants—what do they say?",
 "Write a story that begins with a mysterious message.",
 "Describe a new color that no one has ever seen.",
 "Invent a new sport and explain the rules.",
 "Write a dialogue between two unlikely friends.",
 "Describe a day when everything goes backward.",
 "Imagine you are a detective—what is your first case?",
 "Write a story set in the future.",
 "Describe a magical object and its powers.",
 "Invent a new language and write a sentence in it.",
 "Write a story that takes place underwater.",
 "Describe a festival in a faraway land.",
 "Imagine you can fly—where do you go first?",
 "Write a story from the perspective of a tree.",
 "Describe a world where music controls the weather.",
 "Invent a new kind of transportation.",
 "Write a story about a lost treasure.",
 "Describe a character who can time travel.",
 "Imagine you are invisible for a day—what do you do?",
 "Write a story that starts with a dream.",
 "Describe a city in the clouds.",
 "Invent a new board game and explain how to play.",
 "Write a story about a talking animal.",
 "Describe a magical garden.",
 "Imagine you can breathe underwater—what do you discover?",
 "Write a story about a secret club.",
 "Describe a world where everyone speaks in rhyme.",
 "Invent a new kind of food and describe its taste.",
 "Write a story about a mysterious stranger.",
 "Describe a day when gravity stops working.",
 "Imagine you can read minds—what do you learn?",
 "Write a story about a magical book.",
 "Describe a festival of lights.",
 "Invent a new musical instrument.",
 "Write a story about a journey to the center of the earth.",
 "Describe a world where dreams come true.",
 "Imagine you can talk to animals—what do they say?",
 "Write a story about a hidden door.",
 "Describe a magical forest.",
 "Invent a new holiday tradition.",
 "Write a story about a wish that comes true.",
 "Describe a world where everyone can fly.",
 "Imagine you are a superhero—what is your power?",
 "Write a story about a magical friendship.",
 "Describe a city made of glass.",
 "Invent a new kind of festival.",
 "Write a story about a mysterious island.",
 "Describe a world where colors have flavors.",
 "Imagine you can change the weather—what do you do?",
 "Write a story about a magical pet.",
 "Describe a world where everyone has a twin.",
 "Invent a new kind of art.",
 "Write a story about a secret passage.",
 "Describe a world where time moves backward.",
 "Imagine you can talk to the stars—what do they say?",
 "Write a story about a magical journey.",
 "Describe a world where everyone is an artist.",
 "Invent a new kind of celebration.",
 "Write a story about a magical invention.",
 "Describe a world where everyone can sing beautifully.",
 "Imagine you can visit any place in history—where do you go?"
 }
 };
 }
}
